#!/usr/bin/env python

import sys
from crypto.common import frequency

lines = sys.stdin.readlines()

freqs = frequency.count_letters(lines)

frequencies = []

for k, v in freqs.items():
  frequencies.append((k, v))

ordered_freqs = sorted(frequencies, key=lambda x: x[1] )
ordered_freqs.reverse()

for freq in ordered_freqs:
  print(freq[0] + ': ' + str(freq[1]))




